---
- name: Install Node.js 18
  hosts: catalogue
  become: yes
  tasks:
    - name: Install Node.js 18 using dnf
      dnf:
        name: nodejs
        state: present
        enablerepo: nodesource

    - name: Add roboshop user
      user:
        name: roboshop
        state: present
